chembiocrunch/ic50/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
from .forms import FORM_REGISTRY
import re
# settings = {
#             'inhib1': {
#                 'cssClass': 'inhib1',
#                 'message': 'Low total inhibition, values could be inaccurate'
#             },
#             'inhib2': {
#                 'cssClass': 'inhib2',
#                 'message': 'No low inhibition range - values could be inaccurate'
#             },
#             'inhib3': {
#                 'cssClass': 'inhib3',
#                 'message': 'Error, no good line fit found'
#             }
#         }

strin = '^create-ic50/(?P<form_type>' + '|'.join(FORM_REGISTRY) + ')$'

urlpatterns = [
    
    url(r'^(?P<pk>[0-9]+)/(?P<workflow_revision_id>[0-9]+)/(?P<visualisation_id>[0-9]+)/$', views.Ic50LoadingAreaAjax.as_view(), name='ic50_loading_area_ajax'),
    url(r'^(?P<pk>[0-9]+)/(?P<workflow_revision_id>[0-9]+)/heatmap/$', views.IC50HeatmapView.as_view(), name='workflow_ic50_heatmap'),
    url(re.compile(strin).pattern, views.IC50WorkflowCreateView.as_view(), name='workflow_ic50_create'),
    url(r'^(?P<pk>[0-9]+)/(?P<workflow_revision_id>[0-9]+)/ajax-graphs/$', views.Ic50ListViewAjax.as_view(), name='ic50_list_view_ajax'),
    url(r'^(?P<pk>[0-9]+)/ic50-export/(?P<format>[a-zA-Z0-9]+)$', views.Ic50ExportAllView.as_view(), name='ic50_export_graphs'),
    url(r'^(?P<pk>[0-9]+)/ic50visualisation_view/(?P<format>[a-zA-Z0-9]+)/$', views.Ic50VisualisationView.as_view(), name='ic50_visualisation_view'),
    #url(r'^(?P<pk>[0-9]+)/ic50visualisation_view/(?P<format>[a-zA-Z0-9]+)/(?P<marked_as_bad_fit>[0-1]+)$', views.Ic50VisualisationView.as_view(), name='ic50_visualisation_update_view'),
    url(r'^(?P<pk>[0-9]+)/ic50visualisation_view/(?P<format>[a-zA-Z0-9]+)/(?P<comment>[a-zA-Z0-9\s%]+)$', views.Ic50VisualisationView.as_view(), name='ic50_visualisation_update_view'),

 ]

# def javascript_settings():
#     return settings;

chembiocrunch/workflow/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
from django.conf import settings
#if "ic50" in settings.INSTALLED_APPS:
from ic50.views import IC50WorkflowListView
list_view = IC50WorkflowListView

urlpatterns = [
    url(r'^$', IC50WorkflowListView.as_view() , name='workflow_list'),
    url(r'^create/$', views.WorkflowCreateView.as_view(), name='workflow_create'),
    url(r'^(?P<pk>[0-9]+)/workflow_data_mappings_edit/$', views.WorkflowDataMappingEditView.as_view(), name='workflow_data_mappings_edit'),

    #url(r'^(?P<pk>[0-9]+)/ic50graphs/$', workflows.IC50VisualisationView.as_view(), name='workflow_ic50_graphs'),
    url(r'^(?P<pk>[0-9]+)/visualisation_view/(?P<format>[a-zA-Z0-9]+)/$', views.VisualisationView.as_view(), name='visualisation_view'),
    url(r'^create/success/$', TemplateView.as_view(template_name="workflows/workflow_create_success.html"), name='workflow_create_success'),
   # url(r'^(?P<pk>[0-9]+)/visualisation_export/$', workflows.VisualisationExportView.as_view(), name='visualisation_export'),
    url(r'^(?P<pk>[0-9]+)/visualisation_builder/(?P<workflow_revision_id>[0-9]+)/$', views.VisualisationBuilderView.as_view(), name='visualisation_builder'),
    url(r'^(?P<pk>[0-9]+)/visualisation_builder/(?P<workflow_revision_id>[0-9]+)/(?P<visualisation_id>[0-9]+)/$', views.VisualisationUpdateView.as_view(), name='visualisation_update_view'),

    url(r'^(?P<pk>[0-9]+)/(?P<model>workflow|ic50workflow|qpcrworkflow)/archive_workflow/', views.VisualisationAjaxArchiveView.as_view(), name='workflow_ajax_archive'),

]

chembiocrunch/workflow/models.py
from django.db import models
from pandas.io.pytables import get_store
from django_extensions.db.models import TimeStampedModel
from pandas import DataFrame, read_hdf
from django.db.models import get_model
from django.template.defaultfilters import slugify
import json

import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from StringIO import StringIO

from seaborn import plotting_context, set_context
import mpld3
from workflow.basic_units import BasicUnit
from cbc_common.dataframe_handler import  zero_pad_object_id
from cbc_common import dataframe_handler
from django.conf import settings


def get_labels(vis, df):
    return sorted([k for k,v in df[vis.x_axis].value_counts().iterkv()])

def get_none(vis, df):
    return None


#Graph mappings allow the choices field for graphs to be populated and also tell the plotting algo which seaborn function to use as we plot data
GRAPH_MAPPINGS = {
    "bar" : {"xy": False, "name": "Bar", "function" : sns.barplot, "get_label_function" : get_labels},
    "point" : {"xy": False, "name": "Point Plot", "function" : sns.pointplot, "get_label_function" : get_labels},

    "scatter" : {"xy": True, "name": "Scatter", "function" : plt.scatter, "get_label_function" : get_none},
    "linear_reg" : {"xy": True, "name": "Linear Regression", "function" : sns.regplot, "get_label_function" : get_none},
   # "hist" : {"name": "Histogram", "function" : plt.hist},
   # "boxplot" : {"name": "Boxplot", "function" : sns.boxplot},
}






class WorkflowManager(models.Manager):
    '''Manager allows extra functions to be added to the objects of a model so that you can run queries without having to 
    do the query logic inline'''
    def get_user_records(self, user):
        groups_list = user.groups.filter(name__in =["affiliation:sgc", "affiliation:tdi"])
        if  groups_list.count() > 0:
            return self.filter(created_by__groups__name__in=["affiliation:sgc", "affiliation:tdi"])
        else:
            return self.filter(created_by__id=user.id)


    def get_latest_workflow_revision(self, workflow_id):
        return get_model("workflow", "WorkflowDataMappingRevision").objects.filter(workflow_id=workflow_id).order_by("-created")[0]

def my_slug(str):
    return slugify(str).replace("-","_")

class BaseWorkflow(TimeStampedModel):
    pass
    class Meta:
        abstract = True

# Create your models here.
class Workflow(TimeStampedModel):
    '''A workflow is a container for a set of graphs based on one file. It will have its sub objects cloned
    when the user wants a similar graphing dashboard'''
    title = models.CharField(max_length=100)
    uploaded_file = models.FileField(max_length=1024)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    objects = WorkflowManager()
    workflow_type = "workflow"
    archived = models.BooleanField(default=False)

    def get_latest_data_revision(self):
        return get_model("workflow", "Workflow").objects.get_latest_workflow_revision(self.id)

    def create_first_data_revision(self):

        df = dataframe_handler.get_data_frame(self.uploaded_file.file)
        new_workflow_revision = get_model("workflow", "WorkflowDataMappingRevision").objects.create(workflow=self, revision_type=UPLOAD)   
        # types_frame = DataFrame([[str(dtype) for dtype in df.dtypes],], columns=df.dtypes.keys())
        df.to_hdf(new_workflow_revision.get_store_filename("data"), new_workflow_revision.get_store_key(), mode='w', format="table")
        # types_frame.to_hdf(new_workflow_revision.get_store_filename("dtypes"), new_workflow_revision.get_store_key(), mode='w', format="table")


    def get_data_mapping_formset_data(self):
        rev = self.get_latest_data_revision()
        df = rev.get_data()
        extra_data = [{"workflow_id": self.id, "column_id": index,  "name" : name ,"data_type" : df.dtypes[index].name } for index, name in enumerate(df.dtypes.keys())]
        return extra_data



class WorkflowDataMappingRevisionManager(models.Manager):
    def get_mapping_revisions_for_workflow(self, workflow):
        return self.filter(workflow__id=workflow.id)

UPLOAD ="up"
VALIDATE_COLUMNS ="vc"

REVISION_TYPES = (
    (UPLOAD, "Upload"),
    (VALIDATE_COLUMNS, "Validate Columns")
)

class WorkflowDataMappingRevision(TimeStampedModel):

    '''Every time there is a major change to the field names or the data types in 
    the columns of a workflow's data, we store a revision of the workflow.
    These revisions are as far as possible invisible to the user - we just want them to be able
    to switch between different graphs on a workflow not worrying if data is being treated as a label
    or a number.
    '''

    workflow = models.ForeignKey('Workflow', related_name='workflow_data_revisions')
    steps_json = models.TextField(default="[]")
    revision_type = models.CharField(max_length=5)
    x_axis = models.CharField(max_length=100)
    y_axis = models.CharField(max_length=100)
    objects = WorkflowDataMappingRevisionManager()
    
    def get_store(self):
        return get_store('workflows.%s' % (zero_pad_object_id(self.workflow_id),))

    
    def get_store_filename(self, key,):
        return 'workflows.%s.%s' % (zero_pad_object_id(self.workflow_id),key)

    def get_store_key(self):
        return "wfdr%s" % (  zero_pad_object_id(self.id),)

    def get_dtypes(self, where=None):
        if not where:
            filename=self.get_store_filename("dtypes")
            print filename
            return read_hdf(filename,self.get_store_key(),)
        else:
            return read_hdf(self.get_store_filename("dtypes"),self.get_store_key(),where=where)




    def get_data(self, where=None):
        if not where:
            filename=self.get_store_filename("data")
            return read_hdf(filename,self.get_store_key(),)
        else:
            return read_hdf(self.get_store_filename("data"),self.get_store_key(),where=where)

    def get_column_form_data(self):
        df = self.get_data()
        fields = df.columns.to_series().groupby(df.dtypes).groups
        fields_dict = {k.name: v for k, v in fields.items()}
        string_field_uniques = []
        choices_overall =  []
        for field in fields_dict.get("object",[]):
            s = df[field].value_counts()
            string_field_uniques.append({"name": field,"initial":[k for k,v in s.iterkv()], "choices" : [(k,k) for k,v in s.iterkv()]})
            choices_overall.append((field, "%s (label)" % field))
        numeric_field_max_and_min = []
        for field in fields_dict.get("float64",[]):
            numeric_field_max_and_min.append({"name" : field, "max" : s.max(), "min" : s.min(), "initial_min" :s.min(),"initial_max" : s.max() })
            choices_overall.append((field, "%s (decimal)" % field))
        for field in fields_dict.get("int64",[]):
            numeric_field_max_and_min.append({"name" : field, "max" : s.max(), "min" : s.min(), "initial_min" :s.min(),"initial_max" : s.max() })
            choices_overall.append((field, "%s (whole number)" % field))  

        return {
        "split_by": None,
        "split_colour_by": None,
        "split_y_axis_by": None,
        "visualisation_type" : "bar",
        "visualisation_title" : "",
        "x_axis": self.x_axis, "y_axis": self.y_axis, "string_field_uniques" : string_field_uniques,"numeric_field_max_and_min" :numeric_field_max_and_min , "names" : choices_overall}




class VisualisationManager(models.Manager):
    '''Retrieves visible lists of workflows using the revision id'''
    def by_workflow(self, workflow):
        return self.filter(data_mapping_revision__workflow_id=workflow.id).order_by("-created")

    def by_workflow_revision(self, workflow_revision):
        return self.filter(data_mapping_revision_id=workflow_revision.id).order_by("-created")




class Visualisation(TimeStampedModel):
    '''Holder object for a visualisation
    loosely bound to the visulaisation form
    html field contains a cached svg representation of the visualisation'''
    GRAPH_TYPE_CHOICES = [(key, value["name"]) for key, value in GRAPH_MAPPINGS.iteritems()]
    data_mapping_revision = models.ForeignKey('WorkflowDataMappingRevision', related_name="visualisations")
    x_axis = models.CharField(max_length=200)
    y_axis = models.CharField(max_length=200)
    split_by = models.CharField(max_length=200, null=True, blank=True, default=None)
    split_colour_by = models.CharField(max_length=200, null=True, blank=True, default=None)
    split_y_axis_by = models.CharField(max_length=200, null=True, blank=True, default=None)
    error_bars = models.NullBooleanField()
    visualisation_title = models.CharField(max_length=200, null=True, blank=True)
    visualisation_type = models.CharField(max_length=10, choices=GRAPH_TYPE_CHOICES)
    config_json = models.TextField(default="{}")
    html = models.TextField(default="")
    objects = VisualisationManager()


    def get_svg(self):
        imgdata = StringIO()
        fig = self.get_fig_for_dataframe()
        fig.savefig(imgdata, format='svg')
        imgdata.seek(0)
        return imgdata.buf


    def get_fig_for_dataframe(self):
        form_data = self.get_column_form_data()
        string_expressions = {form_datum["name"] : form_datum["initial"] for form_datum in form_data["string_field_uniques"]}
        df = self.data_mapping_revision.get_data()
        row_mask = df.isin(string_expressions)[[form_datum["name"]  for form_datum in form_data["string_field_uniques"]]]
        df = DataFrame(df[row_mask.all(1)])
        split_y_axis_by = self.split_y_axis_by if self.split_y_axis_by !='None' else None
        split_colour_by = self.split_colour_by if self.split_colour_by !='None' else None

        kwargs = {"size": 5, 
                    "aspect": 1.75,
                     "sharex":True, 

chembiocrunch/workflow/views/forms.py
from django import forms    
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Fieldset
from django.db.models import get_model 
import magic


class CreateWorkflowForm(forms.ModelForm):
    title = forms.CharField(max_length=50)
    uploaded_file  = forms.FileField()









    def clean_uploaded_file(self):
        uploaded_file = self.cleaned_data['uploaded_file']
        mime = magic.from_buffer(uploaded_file.read(), mime=True)
        if 'text/' not in mime:
            raise forms.ValidationError('File must be a CSV document')
        return uploaded_file

    class Meta:
        model = get_model("workflow", "workflow")
        exclude = ('created_by',)





    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.add_input(Submit('save', 'Save'))
        self.helper.layout = Layout(
            Fieldset( '',
                'title', 'uploaded_file', 
                'save',
         )
        )
        
        self.request = kwargs.pop('request', None)
        return super(CreateWorkflowForm, self).__init__(*args, **kwargs)

chembiocrunch/workflow/templates/visualise/vis_new.html
{{ html|safe }}

chembiocrunch/workflow/templates/visualise/visualisation_builder.html
{% extends base_html|default:'workflow_base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load svg_responsive %}




{% block action_title %}
Visualisation Builder

{% endblock  %}


{% block help_text %}

<p>
 
        The visualisation builder lets you create, save and export multiple visualisations
</p>



{% endblock help_text %}
{% block content %}

<form  action="#options" class="  " method="post">

{% include "visualise/visualisation_list.html" %}

{% include "visualise/visualisation_dropdowns.html" %}

<a name="options"/>
<h2 class="row">
<div class="col-lg-2 col-md-2 col-sm-2 hidden-xs">
    {% if not visualisation_id %}
    Adding
    {% else %}
    Editing 
    {% endif %}
</div>
<span style="font-size:12pt">
  {% if visualisation_form %}
    {% crispy visualisation_form visualisation_form.titlehelper %}   
{% endif %}
 <button type="submit"  id="submit-id3-submit"  class="btn btn-primary"></span>Update</button>
</span>
</h2>
<div class="row pull-left col-xs-12">
    {% if visualisation_form %}
        {% crispy visualisation_form visualisation_form.xhelper %}
    {% endif %}
</div>
<div class="row  ninehundred">
    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 ninehundred">
          {{ visualisation.html|add_responsive_tags|safe }}
              {% if visualisation_form %}
                  {% crispy visualisation_form visualisation_form.helper %}
              {% endif %}
          </div>
</div>               
 
{% include "visualise/visualisation_filter.html" %} 


  </form>

{% endblock content %}


{% block extra_js %}
<script>

$(document).ready(function() {

  $(".well").each(function(index){
     message = $(this).attr("message");

  });

});

</script>


{% endblock extra_js %}

chembiocrunch/workflow/templates/visualise/visualisation_dropdowns.html
{% if visualisation_id %}
<div class="dropdown pull-right">
  <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Export
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

    
    <li role="presentation"> <a href="{% url "visualisation_view" pk=visualisation.id format="ppt" %}" role="menuitem" tabindex="-1"  type="link"  id="submit-id3-submit"  class=" btn btn-default input-block-level">As powerpoint</a>

</li>


<!--          <button type="submit"  value="new" name="new" id="submit-id2-submit"  class="btn btn-success"><span class="glyphicon glyphicon-plus"></span></button>
 -->         <li role="presentation"><a href="{% url "visualisation_view" pk=visualisation.id format="png" %}" class="btn btn-default input-block-level" type="link" value="new" name="new" role="menuitem" tabindex="-1" href="#">As png image</a></li>


    <li role="presentation"><a href="{% url "visualisation_view" pk=visualisation.id format="svg" %}" role="menuitem" tabindex="-1" type="link" id="submit-id3-submit" value="delete" name="delete" class="btn btn-default input-block-level "></span>As SVG for CorelDraw/Illustrator</a></li>
  </ul>
</div>

    {% else %}

{% endif %}

<div class="dropdown pull-right">
  <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    File
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

    
    <li role="presentation"> <button role="menuitem" tabindex="-1"  type="submit"  id="submit-id3-submit"  class=" btn btn-default input-block-level">Update</button>

</li>
{% if visualisation_id %}

<!--          <button type="submit"  value="new" name="new" id="submit-id2-submit"  class="btn btn-success"><span class="glyphicon glyphicon-plus"></span></button>
 -->         <li role="presentation"><button class="btn btn-default input-block-level"  value="new" name="new" role="menuitem" tabindex="-1" href="#">Create new</a></li>
    {% else %}

{% endif %}

    <li role="presentation" class="divider"></li>
    <li role="presentation"><button type="submit" role="menuitem" tabindex="-1"  id="submit-id3-submit" value="delete" name="delete" class="btn btn-default input-block-level "><span class="glyphicon glyphicon-remove"></span>Discard &amp; restart</button></li>
  </ul>
</div>
 
<script>
window.onload = function(){
  $('.dropdown-toggle').dropdown();
}
</script>

chembiocrunch/workflow/templates/visualise/visualisation_dropdowns_ajax.html
<div class="dropdown pull-right">
  <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Export
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">


    <li role="presentation"><a href="{% url "ic50_export_graphs" pk=pk format="xlsx" %}" role="menuitem" tabindex="-1" type="link" id="submit-id3-submit" value="delete" name="delete" class="btn btn-default input-block-level "></span>Export all workflow graphs as XLSX</a>
    </li>

  </ul>
</div>

 
<script>
window.onload = function(){
  $('.dropdown-toggle').dropdown();
}
</script>

chembiocrunch/workflow/templates/visualise/visualisation_filter.html
 {% load crispy_forms_tags %}
 {% load staticfiles %}

<div style="position:abolute; bottom:200px">
       <!-- <div class="col-lg-4 slide-out-div crispy form-horizontal well"  >
                <a class="handle" ><button class="btn btn-lg btn-info" style="position: absolute;  " id="submit-id3-submit" type="none"><span class="glyphicon glyphicon-cog"></span> Options</button></a>
        Colour form
</div> -->
 <div class="col-lg-4 col-md-4 col-sm-6 col-xs-8 slide-out-div-right crispy form-horizontal well"  >
    <a class="handle-right" href="http://link-for-non-js-users.html"><button style="position: absolute;  " class="btn btn-lg btn-info"  id="submit-id3-submit" type="none"><span class="glyphicon glyphicon-filter"></span> Filter</button></a>
{% if visualisation_form %}
    {% crispy visualisation_form visualisation_form.filterhelper %}
{% endif %}

</div>
</div>



    <script type="text/javascript">
//     $(function(){
//         leftSlide();
// {% if  visualisation_id %}
// {% else %}
// $(".handle").trigger("click");
   
// {% endif  %}
//  });
$(function(){
    rightSlide();    
 });

var botPos = '-400px';
// function leftSlide(){
//   $('.slide-out-div').tabSlideOut({
//             tabHandle: '.handle',                     //class of the element that will become your tab
//             pathToTabImage: '{% static "images/contact_tab.gifUse of getPreventDefault() is deprecated.  Use defaultPrevented instead." %}', //path to the image for the tab //Optionally can be set using css
//             imageHeight: '0px',                     //height of tab image           //Optionally can be set using css
//             imageWidth: '120px',                       //width of tab image            //Optionally can be set using css
//             tabLocation: 'left',                      //side of screen where tab lives, top, right, bottom, or left
//             speed: 100,                               //speed of animation
//             action: 'click',                          //options: 'click' or 'hover', action to trigger animation
//             topPos: botPos,                          //position from the top/ use if tabLocation is left or right
//             leftPos: '1%',                          //position from left/ use if tabLocation is bottom or top
//             fixedPosition: false                      //options: true makes it stick(fixed position) on scroll
//         });
// }
function rightSlide(){
  $('.slide-out-div-right').tabSlideOut({
            tabHandle: '.handle-right',                     //class of the element that will become your tab
            pathToTabImage: '{% static "images/contact_tab.gif" %}', //path to the image for the tab //Optionally can be set using css
            imageHeight: '0px',                     //height of tab image           //Optionally can be set using css
            imageWidth: '120px',                       //width of tab image            //Optionally can be set using css
            tabLocation: 'right',                      //side of screen where tab lives, top, right, bottom, or left
            speed: 100,                               //speed of animation
            action: 'click',                          //options: 'click' or 'hover', action to trigger animation
            topPos: botPos,                          //position from the top/ use if tabLocation is left or right
            rightPos: '1%',                          //position from left/ use if tabLocation is bottom or top
            fixedPosition: false                      //options: true makes it stick(fixed position) on scroll
        });
}



function resizedw(){
    // Haven't resized in 100ms!
            var w = $('.slide-out-div-right').width();
            $('.slide-out-div-right').css({
                //'height' : properties.containerHeight,
                'right' :"-" + (w +40) +"px",
                'bottom' : botPos
              }
            );
            // var l = $('.slide-out-div').width();
            // $('.slide-out-div').css({
            //     //'height' : properties.containerHeight,
            //     'left' : "-" + (l +40) +"px",
            //     'bottom' : botPos
            // });
}

var doit;
window.onresize = function(){
  clearTimeout(doit);
  doit = setTimeout(resizedw, 120);
};




    </script>
                

chembiocrunch/workflow/templates/visualise/visualisation_list.html
{% load svg_responsive %}
{% if visualisation_list %}
<a name="list">
</a>

    <div class='row'>
    {% for visualisation_item in visualisation_list %}
        
        <div title="{{visualisation_item.results}}" class ="btn col-lg-2 col-md-2 col-sd-4 col-xs-6 "><a id="carousel-selector-{{ visualisation_item.id }}" href="{% url request.resolver_match.url_name pk=object.id workflow_revision_id=workflow_revision.id visualisation_id=visualisation_item.id %}#options"><div class="well col-sd-8 col-sd-offset-2 {% ifequal visualisation_item.id visualisation.id %} activeitem {% endifequal %}">
            <div class="row">
            <span class="workflow-title">{% if visualisation_item.visualisation_title %}{{ visualisation_item.visualisation_title|title }}{% else %} no title yet{% endif %}</span></div><div class="row"><span class="workflow-date">{{ visualisation_item.created }}</span>
            </div><div class="vis-thumb ">{{ visualisation_item.html|add_responsive_tags|safe }}</div>
            

        </div></a></div> 
        
    {% endfor %}
</div><!-- end vis holder -->
{% endif %}

chembiocrunch/workflow/templates/visualise/visualise.html
{% load crispy_forms_tags %}

<div class="row">
<div class="col-xs-9" >

<img class="col-xs-9" src="{% url 'visualisation_view' visualisation.id %}"></img>
</div>
<div class="col-xs-3 sidebar-nav">
{% crispy visualisation.vis_option_form visualisation.vis_option_form.helper %}
</div>
<script type="text/javascript">
var div_to_replace = "visualisation_holder_{{ visualisation.id }}";
    
    // $('#button-id-save').click(function(e){
    //     e.preventDefault();
    //     $.get({
    //         url: "{% url 'visualisation_view' visualisation.id %}",
    //         data: {"visualisation": visualisation, "y_axis": y_axis, "x_axis" :x_axis},
    //         success: function(){
    //             alert("success");
    //             $("#result").html('Submitted successfully');
    //         },
    //         error:function(){
    //             alert("failure");
    //             $("#result").html('There is error while submit');
    //         }
    //     })
    // });

    // $('#button-id-export').click(function(e){
    //     e.preventDefault();
    //     $.get({
    //         url: "",
    //         data: {"y_axis": $(".use_as_x_axis").attr(":checked").val(), "x_axis" :$(".use_as_y_axis").attr(":checked").val()}, //is the graph in the workflow object?l
    //         success: function(){
    //             alert("success");
    //             $("#result").html('Submitted successfully');
    //         },
    //         error:function(){
    //             alert("failure");
    //             $("#result").html('There is error while submit');
    //         }
    //     })
    // $('#button-id-export').click(function(e){
    //     e.preventDefault();
    //     $.get({
    //         url: "{% url 'visualisation_export' visualisation.id %}",
    //         data: {"y_axis": $(".use_as_y_axis:checked").val(), "x_axis" : $(".use_as_x_axis:checked").val()}, //is the graph in the workflow object?l
    //         success: function(){
    //             alert("success");
    //             $("#result").html('Submitted successfully');
    //         },
    //         error:function(){
    //             alert("failure");
    //             $("#result").html('There is error while submit');
    //         }
    //     });
    //     return false;

    // });
    
    // $.ajax({
    //     url: "{% url 'visualisation_view' visualisation.id %}",
    //     type: "get",
    //     data: {},
    //     success: function(data){
    //         var elem =  document.getElementById(div_to_replace);
    //         elem.src = "data:image/png;base64," + data;
    //     },
    //     error:function(){
    //         alert("failure");
    //         $("#result").html('There is error while submit');
    //     }
    // });

    /*$.ajax({
        url: "{% url 'visualisation_view' visualisation.id %}",
        type: "get",
        data: {},
        success: function(){
            alert("success");
            $("#result").html('Submitted successfully');
        },
        error:function(){
            alert("failure");
            $("#result").html('There is error while submit');
        }
    });*/
    

</script>
</div>